vi install.yml
---
- hosts: all 
  tasks:
  - name: Install httpd Package
    yum: name=httpd state=latest
  - name: Copy httpd configuration file
    copy: src=/data/httpd.original dest=/etc/httpd/conf/httpd.conf
  - name: Start and Enable httpd service
    service: name=httpd state=restarted enabled=yes 


    